### PR TITLE
Clarify use of MedicationRequest.quantity and quantityText

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by martinhillyard** [comment]
Revised text looks much better, happy with that. Could we come up with some other examples though as 84 tablet(s) looks like something that could be a value and unit. Appreciate that it could also be stored just as a string and the description of the elments explains, but maybe we could see if clinicians have any known examples. I am wondering if there might be some old records that could have something like 'One pack of a dozen tablets'. Anything that looks more like it is a single string.

**Comment by st3v3nhunt** [comment]
I've updated the example to be less value & unit and more 'stringy'. I found it ('quantity varies dependent on schedule') in a test record along with another one ('three millilitres').

**Comment by martinhillyard** [comment]
Really sorry, I should have been clearer. I was also thinking of the examples giving on the accessrecord_structured_development_medicationrequest.md page for the extension. The ones in your previous comment look perfect to be added there if that would be OK. My bad for not actually saying that.

**Comment by st3v3nhunt** [comment]
Done - examples in the guidance have been extended to include the couple of less value+unit ones.

**Review by martinhillyard — APPROVED** [review]

**Pull request merged**
